[phases.setup]
nixPkgs = ["nodejs", "npm", "curl"]

[phases.install]
cmds = [
  "npm ci",
  "cd client && npm ci"
]

[phases.build]
cmds = [
  "cd client && npm run build"
]

[start]
cmd = "npm run start:prod"
