[phases.setup]
nixPkgs = ["nodejs", "npm", "curl"]

[phases.install]
cmds = [
  "npm install",
  "cd client && npm install"
]

[phases.build]
cmds = [
  "cd client && npm run build"
]

[start]
cmd = "npm run start:prod"

[providers]
railway = { healthcheckPath = "/health", healthcheckTimeout = 30000 }
