[build]
builder = "nixpacks"

[deploy]
startCommand = "npm run start:prod"
healthcheckPath = "/health"
healthcheckTimeout = 30000
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
PORT = "3001"
DATABASE_URL = "postgresql://postgres:uWGyYCeOFFMRlexEzJBRjvCgoUWeYtkl@ballast.proxy.rlwy.net:35894/railway"
REACT_APP_API_URL = "https://web-production-c1c01.up.railway.app/api"
